### ISSUE TITLE
improve library build script

### ISSUE THREAD

**Issue by lars2015** [slcs-jsc/mptrac#17]
**Is your feature request related to a problem?**
- the library build script (`libs/build.sh`) can be improved by additional functionality

**Describe the solution you'd like**
- add a command line argument so that the number of threads for parallel builds can be selected (`make -j<nthreads>')
- add command line arguments so that the user can select which libraries to build (to avoid time-consuming builds of GSL or netCDF, if the software is already available)
- add an option to download the tarballs of the libraries from their respective sources from the web rather than including them in the MPTRAC git repository?
- perhaps implement this as a Makefile rather than a bash script?

**Additional context**
- pull request by Yen-Sen: https://github.com/slcs-jsc/mptrac/pull/14

**Comment by hydrogencl** [comment]
- The `args` using different number of threads can be done by the script with `build.sh -p $NUMBER_OF_CORES`. 

 - The selection with libraries can be done with `args`, e.g `./build.sh -g` to build with only GSL Library. 

- makefile + download from the "official repo": can try the solution from the ICON installation by using the `git submodule -init`.

**Comment by lars2015** [comment]
Hi Yen-Sen,

I think we want a new target like `-m` to build the mandatory set of libs, only. This would include GSL, netCDF, HDF5, and zlib.

So, most users would be happy using the `-m` flag for building the libs and only those who want extra things like zfp, zstd, thrust, kpp would use `-a` to build all the libraries.

Best regards
Lars

**Comment by hydrogencl** [comment]
I think we should close this issue and using the issue #31 instead of this one.
