### ISSUE TITLE
 Accelerator restriction: call to 'phot_rate' with no acc routine information

### ISSUE THREAD

**Issue by hydrogencl** [slcs-jsc/mptrac#21]
From ESM-Buildbot this issue happens to the GPU building. 
The CPU building pass this issue.

**Comment by lars2015** [comment]
Hi Yen-Sen,

thanks for pointing this out. Can you please check back with Mingzhao to check this? Maybe only some OpenACC pragmas for the new tracer chemistry code developed by Mingzhao are missing.

Best, Lars

**Comment by hydrogencl** [comment]
Great. We will close this issue once @laomangio fix this. I will keep tracking this.

**Comment by laomangio** [comment]
Thank you for reminder. I have push the fixing.

**Comment by hydrogencl** [comment]
The buildbot shows "pass". Issue close
Thanks @laomangio !
