### ISSUE TITLE
Python code examples

### ISSUE THREAD

**Issue by lars2015** [slcs-jsc/mptrac#29]
**Is your feature request related to a problem?**
- Provide some simple examples of python scripts helping new users to work with MPTRAC simulation output.

**Describe the solution you'd like**
- Examples should show how to read atm- and grid-files in ASCII file format and make map plots of the data.
- Put Python code examples in a new directory ./projects/python

**Additional context**
- Add some context on python usage to the mkdocs documentation?

**Comment by laomangio** [comment]
I have put the python plot scripts in projects/example to use the atm and grid output in example/data.

**Comment by lars2015** [comment]
Hi Mingzhao,

thank you for sharing the python plot scripts.

Can you please put them in the separate directory `./projects/python`, as said above?

I do not want to merge it with the example.

Best regards
Lars

**Comment by lars2015** [comment]
Hi Mingzhao,

thanks for fixing the path.

Perhaps you could add a README.md file providing a few sentences about what the scripts are doing and which prerequisites are necessary to run them?

For example, I found I had to install these packages on Ubuntu 22.04 to create the plots:
```
sudo apt install python-is-python3 python3-cartopy python3-opencv
```

Best regards
Lars

**Comment by lars2015** [comment]
Hi Mingzhao,

I modified the grid output to include the standard deviations and sorted the columns in a different way.

Can you please update the python example for the grid output? (I could not figure out how you select the column that is to be plotted.)

Thanks
Lars

**Comment by fkhosrawi** [comment]
Hi Mingzhao, Hi Lars,

I  have a suggestion on the header of our example codes. In one of our Python meetings at KIT I learned that code headers should look as follows:

""""
Author: Farahnaz Khosrawi
Data created: 17.10.2023
Last modified: 17.10.2023
Purpose: Find the trajectory index for the trajectory with the largest differences to the reference and plot locations of these on a map
""""

Thus, adding some kind of history (when written and changed) and a short description what the code is doing additionally to the information of the author of the code.  Would that be something we could/should do for our example codes as well? What do you think? 

Best wishes, Farah

**Comment by lars2015** [comment]
Hi Farah,

this is a very nice idea, yes, let's do that!

Lars

**Comment by lars2015** [comment]
Hello,

Fixed some minor code issues found by static code analysis.

It seems we can close this issue now.

Best regards
Lars
