### ISSUE TITLE
./build.sh nc4

### ISSUE THREAD

**Issue by Tompythonorange** [slcs-jsc/mptrac#4]
after ./build.sh nc4,there are some errors, but ./build.sh nc2 is no problem

***** 12 FAILURES! *****
Command exited with non-zero status 1
0.34user 0.29system 0:00.62elapsed 103%CPU (0avgtext+0avgdata 4236maxresident)k
0inputs+0outputs (0major+18632minor)pagefaults 0swaps
Makefile:3451: recipe for target 'dt_arith.chkexe_' failed
make[4]: *** [dt_arith.chkexe_] Error 1
make[4]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
Makefile:3436: recipe for target 'build-check-s' failed
make[3]: *** [build-check-s] Error 2
make[3]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
Makefile:3431: recipe for target 'test' failed
make[2]: *** [test] Error 2
make[2]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
Makefile:3207: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
Makefile:715: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
root@LAPTOP-9C6L8HRA:/usr/local/meteo/mptrac/libs# cd build/
![image](https://user-images.githubusercontent.com/39429729/159126852-2e037db2-e3a7-4027-99c4-7a7ce1b65b59.png)

**Comment by lars2015** [comment]
Hello,

we recommend using the `./libs/build.sh` script to build the GSL and netCDF versions provided via the MPTRAC repository to make sure everyone uses the same versions of the libraries. Unfortunately, building netCDF-4 (`nc4` option) is tricky, as it depends on HDF5 and zlib. From your log message, it seems the build checks of the HDF5 library failed.

We build MPTRAC regularly on different Linux systems (e.g., Ubuntu 20.04 LTS), there are currently no known issues. Which operating system are you using?

If your OS provides a development package for netCDF, it might be easiest to use it to compile MPTRAC. You can use `nc-config --all` to get the include and library paths and edit `./src/Makefile` to use the netCDF library already available on your system.

If you like to try fixing the current issue, you might want to check the log file `./libs/build/src/hdf5-1.12.1/config.log`, to see if there are any errors.

This link suggests compiling HDF5 with a lower optimization level to fix the first error you found: https://support.hdfgroup.org/HDF5/release/known_problems/previssues.html

Please let me know if you got it running.

Best regards
Lars

**Comment by Tompythonorange** [comment]
> Hello,
> 
> we recommend using the `./libs/build.sh` script to build the GSL and netCDF versions provided via the MPTRAC repository to make sure everyone uses the same versions of the libraries. Unfortunately, building netCDF-4 (`nc4` option) is tricky, as it depends on HDF5 and zlib. From your log message, it seems the build checks of the HDF5 library failed.
> 
> We build MPTRAC regularly on different Linux systems (e.g., Ubuntu 20.04 LTS), there are currently no known issues. Which operating system are you using?
> 
> If your OS provides a development package for netCDF, it might be easiest to use it to compile MPTRAC. You can use `nc-config --all` to get the include and library paths and edit `./src/Makefile` to use the netCDF library already available on your system.
> 
> If you like to try fixing the current issue, you might want to check the log file `./libs/build/src/hdf5-1.12.1/config.log`, to see if there are any errors.
> 
> This link suggests compiling HDF5 with a lower optimization level to fix the first error you found: https://support.hdfgroup.org/HDF5/release/known_problems/previssues.html
> 
> Please let me know if you got it running.
> 
> Best regards Lars

by ubuntu18.04 in windows10, config.log it seems no problem

**Comment by lars2015** [comment]
This issue was closed with issue #6.
