### ISSUE TITLE
python plot scripts

### ISSUE THREAD

**Issue by lars2015** [slcs-jsc/mptrac#44]
There seems to be an issue with installing matplotlib for the python plot scripts on Ubuntu 24.04?

```
> sudo apt install python3-mpltoolkits.basemap
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-mpltoolkits.basemap is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by hydrogencl** [comment]
I think for python packages, it would be better to use `python3 -m pip install basemap`, which is also stated in the [basemap repo](https://github.com/matplotlib/basemap) .

**Comment by lars2015** [comment]
Hi Yen-Sen,

Installing basemap globally with pip did not work directly for me, Ubuntu 24.04 requires the python modules to be installed in a virtual environment (venv), it seems. I've updated the README and example scripts to reflect this.

Thanks! :-)
Lars
