### ISSUE TITLE
../build.sh nc4 error always

### ISSUE THREAD

**Issue by Tompythonorange** [slcs-jsc/mptrac#5]
when I change ubuntu version to Ubuntu 20.04.4 LTS by windows10
after ./build.sh nc4 , there are also some problems:
***** 12 FAILURES! *****
Command exited with non-zero status 1
0.37user 0.20system 0:00.61elapsed 94%CPU (0avgtext+0avgdata 4200maxresident)k
0inputs+0outputs (0major+18348minor)pagefaults 0swaps
make[4]: *** [Makefile:3451: dt_arith.chkexe_] Error 1
make[4]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
make[3]: *** [Makefile:3437: build-check-s] Error 2
make[3]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
make[2]: *** [Makefile:3431: test] Error 2
make[2]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
make[1]: *** [Makefile:3208: check-am] Error 2
make[1]: Leaving directory '/usr/local/meteo/mptrac/libs/build/src/hdf5-1.12.1/test'
make: *** [Makefile:715: check-recursive] Error 1
![image](https://user-images.githubusercontent.com/39429729/159704505-4d97dc7c-e97a-4e26-8fef-f0221ea1a2e9.png)

**Comment by lars2015** [comment]
This issue was closed with issue #6.
